DYNAMICZNIE I SILNIE TYPOWANY PROGRAM;
DOMYŚLNE PRZEKAZYWANIE REFERENCJI DO OBIEKTÓW -> DODAĆ FUNKCJĘ .copy()
DOMYŚLNIE WSZYSTSKIE ZMIENNE MUTOWALNE
- program                           = {function_definition};
- function_definition               = "fun", ["->", type] identifier, "(" [identifier, {",", identifier}], ")", "{", {statement}, "}"; 
- statement                         = while_loop | for_loop | if_statement | variable_instantiation | list_declaration | value_assignment | (expression, ";") | return_statement | "break;" | "continue;";
- return_statement                  = "return", [expression], ";";

(*CODE BLOCKS*)
- while_loop                        = "while", expression,  "{", {statement}, "}";
- for_loop                          = "for", identifier, "in", (identifier | function_call | string | list), "{", {statement}, "}";
- if_statement                      = "if", expression ,"{", {statement}, "}", {"else if", expression, "{", {statement}, "}"}, ["else", "{", {statement}, "}"];

(*STATEMENTS*)
- function_call                     = identifier, "(" [expression], {",", expression}, ")";
- variable_instantiation            = "var", identifier, ["=", expression], ";";
- list_access                       = expression, "[", expression, "]";
- value_assignment                  = expression, "=", expression, ";";

(*EXPRESSION*)
- expression                        = or_operand, {"||", or_operand};
- or_operand                        = xor_operand, {"#", xor_operand};
- xor_operand                       = and_operand, {"&&", and_operand};
- and_operand                       = comparison_operand, [("==" | "!=" | "<" | ">" | "<=" | ">="), comparison_operand];
- comparison_operand                = addend, {("+" | "-"), addend};
- addend                            = [!], term, {("*" | "/"), [!], term};
- term                              = exponentiation_operand, {"^", exponentiation_operand};
- exponentiation_operand            = ("(", expression, ")") | literal | identifier | function_call | list_access;

(*SIMPLE DEFINITIONS*)
- identifier                        = ["_"], letter, {"_" | letter | digit};
- letter                            = "a" | "b" | "c" | ... | "z" | "A" | "B" | "C" | ... | "Z";
- literal                           = integer | float | string | bool | list; 
- type                              = "int"  | "float" | "string" | "bool" | "list";
- list                              = "[" expression, {",", expression} "]";
- bool                              = "True" | "False";
- string                            = "\"" , {letter} | " " | {special_character} | {new_line} | escaped_character, "\"";
- escaped_character                 = "\", special_character | "n" | "r";
- special_character                 = "!" | "\"" | "#" | "$" | ... | "/" | ":" | ";" | ... | "@" | "[" | ... | "'" | "{" | "~";
- new_line                          = "\n" | "\r" | "\r\n"; 
- float                             = integer , "." , digit, {digit};
- integer                           = non_zero_digit | {digit};
- digit                             = "0" | non_zero_digit;
- non_zero_digit                    = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
(*comment                           = "//" means ignore all characters afterward, until newline occurs or end of file*)

obsługa liczb o różnej precyzji (np. Float32, Float64)
